### ISSUE TITLE
Error on install

### ISSUE THREAD

**Issue by therampagerado** [thirtybees/overridecheck#1]
[PrestaShop] Fatal error in module file :/home/user/domain/modules/overridecheck/overridecheck.php:
require_once(): Failed opening required '/home/user/domain/modules/overridecheck/vendor/autoload.php' (include_path='/home/user/domain/vendor/pear/archive_tar:/home/user/domain/vendor/pear/console_getopt:/home/user/domain/vendor/pear/pear-core-minimal/src:/home/user/domain/vendor/pear/pear_exception:.:/opt/alt/php70/usr/share/pear')

Do I have to use it with only PHP 5.6?

**Comment by firstred** [comment]
No, you will need to run the build script before you install it: https://github.com/thirtybees/overridecheck/blob/e668aa1e1ccfb82c24b77e15d3dbd8a1f08d1d29/build.sh
